// LANDING TYPES
export const GET_LANDING_DATA = "GET_LANDING_DATA";
export const SET_LANDING_STATUS = "SET_LANDING_STATUS";

// SEARCH WIDGET
export const SET_QUERY = "SET_QUERY";
export const SAVE_QUERY = "SAVE_QUERY";
export const SEARCH_LOADING = "SEARCH_LOADING";

// SEARCH RESULT TYPES
export const SEARCH_RESULT_OVERVIEW = "SEARCH_RESULT_OVERVIEW";
export const GET_INDIVIDUAL_SCHOOL = "GET_INDIVIDUAL_SCHOOL";
export const CLEAR_DATA = "CLEAR_DATA";

// INDIVIDUAL SCHOOL
export const GET_SCHOOL_RECORD = "GET_SCHOOL_RECORD";
export const GET_SCHOOL_CHAMPIONSHIPS = "GET_SCHOOL_CHAMPIONSHIPS";
export const GET_SCHOOL_NBA = "GET_SCHOOL_NBA";
